// Code generated by MockGen. DO NOT EDIT.
// Source: mockeableInterface.go

// Package mock_main is a generated GoMock package.
package main

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMockeableInterface is a mock of MockeableInterface interface.
type MockMockeableInterface struct {
	ctrl     *gomock.Controller
	recorder *MockMockeableInterfaceMockRecorder
}

// MockMockeableInterfaceMockRecorder is the mock recorder for MockMockeableInterface.
type MockMockeableInterfaceMockRecorder struct {
	mock *MockMockeableInterface
}

// NewMockMockeableInterface creates a new mock instance.
func NewMockMockeableInterface(ctrl *gomock.Controller) *MockMockeableInterface {
	mock := &MockMockeableInterface{ctrl: ctrl}
	mock.recorder = &MockMockeableInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMockeableInterface) EXPECT() *MockMockeableInterfaceMockRecorder {
	return m.recorder
}

// GetGreeting mocks base method.
func (m *MockMockeableInterface) GetGreeting(arg0 string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGreeting", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetGreeting indicates an expected call of GetGreeting.
func (mr *MockMockeableInterfaceMockRecorder) GetGreeting(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGreeting", reflect.TypeOf((*MockMockeableInterface)(nil).GetGreeting), arg0)
}
